# Site settings
title: This Is Blog
description: Such Blog. Much Posts. Wow.
email: paul.nesbitt@erdosmiller.com
phone: (832)489-8434
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pnesbitt.github.io" # the base hostname & protocol for your site
github: pnesbitt
github_URL: https://github.com/pnesbitt
linkedIn: Paul Nesbitt
linkedIn_URL: http://www.linkedin.com/pub/paul-nesbitt/25/447/29a/

# Build settings
markdown: kramdown
highlighter: rouge